apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
    spec:
      containers:
      - name: crashloop-container
        image: busybox
        command: ["sh", "-c", "echo CrashLoopBackOff; exit 1"]